Added tests
phonetworks/pho-server-rest pull request #1
Opened 2017-08-23 12:56 UTC by poratuk

2017-08-23 12:57 UTC, poratuk commented
This task are not completed:
please look on https://github.com/poratuk/pho-server-rest/blob/complete-tests/tests/NodeRoutesTest.php#L75 

I do not shure how must be added Edge and what parameters must be sended.

2017-08-26 07:16 UTC, esokullu requested changes

2017-08-26 07:16 UTC, esokullu commented on tests/NodeRoutesTest.php
> +    public function testGetNonExsitingEdge()
Existing, not Exsiting

2017-08-26 07:16 UTC, esokullu commented on tests/EntityRoutesTest.php
> +    public $founder_id = '';
why public? let's keep privileges as minimal as possible.

2017-08-26 07:16 UTC, esokullu commented on tests/NodeRoutesTest.php
> +    public function testCreateEdge()
what about "like" that i told you?

2017-08-26 07:16 UTC, esokullu commented on tests/TestCase.php
> +    protected function post(string $path, array $postData)
i would add $headers similarly to the get function and make them behave similarly, for consistency purposes.

2017-08-26 07:16 UTC, esokullu commented on tests/TestCase.php
> +    {
same as above...

2017-08-28 10:30 UTC, esokullu approved these changes

2017-08-28 10:30 UTC, merged